name: plugin-gary-mock-server
description: Adiciona uma pasta com um mock server para nao depender de servidores online
display-name: plugin-gary-mock-server
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - docker
  - angular
  - java
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
